# doc_sections_part2.py - Chapter 2: PostgreSQL 16 DDL Script

def get_part2():
    lines = []
    w = lines.append

    w("# CHƯƠNG 2: PHẦN I — TOÀN VĂN KỊCH BẢN DDL POSTGRESQL 16 (FULL SCHEMA SCRIPT)")
    w("")
    w("> [!NOTE]")
    w("> Toàn bộ kịch bản DDL dưới đây có thể thực thi độc lập trên PostgreSQL 16+. Cú pháp được chuẩn hóa với các lệnh `IF NOT EXISTS` và `DO $$ ... $$` an toàn cho việc khởi tạo lặp lại.")
    w("")
    w("```sql")
    w("-- ============================================================================")
    w("-- SMART F&B OPERATING SYSTEM (v2.5.0) - PRODUCTION DATABASE DDL SCRIPT")
    w("-- Engine: PostgreSQL 16 Enterprise | Schema: public | Encoding: UTF-8")
    w("-- Standard: 3NF Normalized, UUID v4 PKs, Full FK Constraints & Triggers")
    w("-- ============================================================================")
    w("")
    w("-- ============================================================================")
    w("-- 2.1 EXTENSIONS & KIỂU DỮ LIỆU LIỆT KÊ (ENUMS)")
    w("-- ============================================================================")
    w("")
    w("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")
    w("CREATE EXTENSION IF NOT EXISTS \"pgcrypto\";")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE user_role_enum AS ENUM (")
    w("        'ChainAdmin', ")
    w("        'BranchManager', ")
    w("        'BaristaStaff', ")
    w("        'CashierStaff', ")
    w("        'ServiceStaff'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE order_type_enum AS ENUM (")
    w("        'DineIn', ")
    w("        'TakeAway', ")
    w("        'Delivery'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE order_status_enum AS ENUM (")
    w("        'PendingPayment', ")
    w("        'Paid', ")
    w("        'Confirmed', ")
    w("        'Preparing', ")
    w("        'Ready', ")
    w("        'Delivering', ")
    w("        'Completed', ")
    w("        'Cancelled'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE payment_method_enum AS ENUM (")
    w("        'VietQR', ")
    w("        'Cash'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE payment_status_enum AS ENUM (")
    w("        'Pending', ")
    w("        'Paid', ")
    w("        'Failed', ")
    w("        'Refunded'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE attendance_status_enum AS ENUM (")
    w("        'OnTime', ")
    w("        'Late', ")
    w("        'Overtime', ")
    w("        'Excused'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE table_status_enum AS ENUM (")
    w("        'Available', ")
    w("        'Occupied', ")
    w("        'AwaitingFood', ")
    w("        'Cleaning', ")
    w("        'Inactive'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE shift_status_enum AS ENUM (")
    w("        'Open', ")
    w("        'Closed', ")
    w("        'Audited'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE modifier_type_enum AS ENUM (")
    w("        'Sweetness', ")
    w("        'Ice', ")
    w("        'Topping', ")
    w("        'MilkOption'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE voucher_discount_type_enum AS ENUM (")
    w("        'Percentage', ")
    w("        'FixedAmount'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE loyalty_transaction_type_enum AS ENUM (")
    w("        'TakeawayAccumulate', ")
    w("        'TakeawayRedeem10Free', ")
    w("        'ManualAdjustment'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("DO $$ BEGIN")
    w("    CREATE TYPE inventory_check_status_enum AS ENUM (")
    w("        'Draft', ")
    w("        'Approved', ")
    w("        'Rejected'")
    w("    );")
    w("EXCEPTION WHEN duplicate_object THEN null; END $$;")
    w("")
    w("-- ============================================================================")
    w("-- 2.2 NHÓM 1: HỆ THỐNG, CƠ SỞ CHI NHÁNH & BÀN PHỤC VỤ QR")
    w("-- ============================================================================")
    w("")
    w("-- BẢNG 01: branches (Danh mục chi nhánh toàn chuỗi)")
    w("CREATE TABLE IF NOT EXISTS branches (")
    w("    branch_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    code VARCHAR(50) NOT NULL UNIQUE,")
    w("    name VARCHAR(150) NOT NULL,")
    w("    address VARCHAR(300) NOT NULL,")
    w("    phone VARCHAR(20) NOT NULL,")
    w("    operating_hours VARCHAR(100) NOT NULL DEFAULT '07:00 - 22:30',")
    w("    is_active BOOLEAN NOT NULL DEFAULT TRUE,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
    w(");")
    w("")
    w("COMMENT ON TABLE branches IS 'Quản lý danh mục các chi nhánh F&B trong toàn chuỗi';")
    w("COMMENT ON COLUMN branches.code IS 'Mã định danh duy nhất chi nhánh (ví dụ: CN-Q1-HCM, CN-CG-HN, CN-HC-DN)';")
    w("")
    w("-- BẢNG 02: branch_wifi_configs (Cấu hình BSSID & IP Subnet chấm công)")
    w("CREATE TABLE IF NOT EXISTS branch_wifi_configs (")
    w("    wifi_config_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    branch_id UUID NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,")
    w("    ssid_name VARCHAR(100) NOT NULL,")
    w("    bssid_list TEXT NOT NULL,")
    w("    allowed_ip_subnets TEXT NOT NULL,")
    w("    is_active BOOLEAN NOT NULL DEFAULT TRUE,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE branch_wifi_configs IS 'Khai báo thông số phần cứng Router WiFi chi nhánh dùng chấm công Dual-Factor';")
    w("COMMENT ON COLUMN branch_wifi_configs.bssid_list IS 'Danh sách MAC Address Access Point WiFi ngăn cách bởi dấu phẩy';")
    w("COMMENT ON COLUMN branch_wifi_configs.allowed_ip_subnets IS 'Dải địa chỉ IP Gateway nội bộ chuẩn CIDR (ví dụ: 192.168.1.0/24)';")
    w("")
    w("-- BẢNG 03: tables (Sơ đồ bàn phục vụ tại quán & QR Code)")
    w("CREATE TABLE IF NOT EXISTS tables (")
    w("    table_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    branch_id UUID NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,")
    w("    table_number VARCHAR(50) NOT NULL,")
    w("    zone_name VARCHAR(50) NOT NULL DEFAULT 'Indoor',")
    w("    capacity INT NOT NULL DEFAULT 4 CHECK (capacity > 0),")
    w("    qr_token VARCHAR(100) NOT NULL UNIQUE,")
    w("    qr_code_url VARCHAR(500),")
    w("    status table_status_enum NOT NULL DEFAULT 'Available',")
    w("    is_active BOOLEAN NOT NULL DEFAULT TRUE,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    CONSTRAINT uq_branch_table_number UNIQUE (branch_id, table_number)")
    w(");")
    w("")
    w("COMMENT ON TABLE tables IS 'Quản lý danh mục bàn ăn tại từng chi nhánh và mã định danh QR gắn bàn';")
    w("")
    w("-- ============================================================================")
    w("-- 2.3 NHÓM 2: NGƯỜI DÙNG, PHÂN QUYỀN RBAC & NHẬT KÝ KIỂM TOÁN")
    w("-- ============================================================================")
    w("")
    w("-- BẢNG 04: users (Tài khoản nhân sự và quản trị viên)")
    w("CREATE TABLE IF NOT EXISTS users (")
    w("    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    branch_id UUID REFERENCES branches(branch_id) ON DELETE SET NULL,")
    w("    user_code VARCHAR(50) NOT NULL UNIQUE,")
    w("    username VARCHAR(100) NOT NULL UNIQUE,")
    w("    password_hash VARCHAR(255) NOT NULL,")
    w("    full_name VARCHAR(150) NOT NULL,")
    w("    email VARCHAR(150),")
    w("    phone VARCHAR(20),")
    w("    avatar_url VARCHAR(500),")
    w("    status VARCHAR(50) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive', 'Suspended')),")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
    w(");")
    w("")
    w("COMMENT ON TABLE users IS 'Danh mục tài khoản nhân viên, quản lý chi nhánh và chủ chuỗi';")
    w("COMMENT ON COLUMN users.password_hash IS 'Mật khẩu băm chuẩn BCrypt (Cost factor 11)';")
    w("")
    w("-- BẢNG 05: roles (Danh mục vai trò định danh hệ thống)")
    w("CREATE TABLE IF NOT EXISTS roles (")
    w("    role_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    role_name VARCHAR(50) NOT NULL UNIQUE,")
    w("    description VARCHAR(255),")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE roles IS 'Định nghĩa 5 vai trò hệ thống: ChainAdmin, BranchManager, BaristaStaff, CashierStaff, ServiceStaff';")
    w("")
    w("-- BẢNG 06: user_roles (Bảng liên kết phân quyền người dùng - vai trò)")
    w("CREATE TABLE IF NOT EXISTS user_roles (")
    w("    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,")
    w("    role_id UUID NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,")
    w("    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    PRIMARY KEY (user_id, role_id)")
    w(");")
    w("")
    w("COMMENT ON TABLE user_roles IS 'Phân bổ vai trò RBAC cho từng tài khoản người dùng';")
    w("")
    w("-- BẢNG 07: audit_logs (Nhật ký kiểm toán hệ thống bất biến - Append-Only)")
    w("CREATE TABLE IF NOT EXISTS audit_logs (")
    w("    audit_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    user_id UUID REFERENCES users(user_id) ON DELETE SET NULL,")
    w("    action VARCHAR(100) NOT NULL,")
    w("    entity_name VARCHAR(100) NOT NULL,")
    w("    entity_id VARCHAR(100) NOT NULL,")
    w("    old_values JSONB,")
    w("    new_values JSONB,")
    w("    ip_address VARCHAR(50),")
    w("    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE audit_logs IS 'Lưu vết kiểm toán bất biến phục vụ an ninh và đối soát thay đổi dữ liệu nhạy cảm';")
    w("")
    w("-- ============================================================================")
    w("-- 2.4 NHÓM 3: THỰC ĐƠN, BIẾN THỂ KÍCH CỠ, BẢNG GIÁ VÙNG & TÙY CHỌN MODIFIERS")
    w("-- ============================================================================")
    w("")
    w("-- BẢNG 08: categories (Danh mục món ăn/đồ uống)")
    w("CREATE TABLE IF NOT EXISTS categories (")
    w("    category_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    code VARCHAR(50) NOT NULL UNIQUE,")
    w("    name VARCHAR(100) NOT NULL,")
    w("    description TEXT,")
    w("    display_order INT NOT NULL DEFAULT 0,")
    w("    image_url VARCHAR(500),")
    w("    is_active BOOLEAN NOT NULL DEFAULT TRUE,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
    w(");")
    w("")
    w("COMMENT ON TABLE categories IS 'Danh mục phân loại thực đơn (Cà phê, Trà sữa, Trà trái cây, Bánh ngọt, Đồ ăn vặt)';")
    w("")
    w("-- BẢNG 09: products (Sản phẩm / Món ăn cơ sở)")
    w("CREATE TABLE IF NOT EXISTS products (")
    w("    product_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    category_id UUID NOT NULL REFERENCES categories(category_id) ON DELETE RESTRICT,")
    w("    sku VARCHAR(50) NOT NULL UNIQUE,")
    w("    name VARCHAR(150) NOT NULL,")
    w("    description TEXT,")
    w("    base_price DECIMAL(12,0) NOT NULL CHECK (base_price >= 0),")
    w("    image_url VARCHAR(500),")
    w("    is_available BOOLEAN NOT NULL DEFAULT TRUE,")
    w("    is_best_seller BOOLEAN NOT NULL DEFAULT FALSE,")
    w("    calories_approx INT DEFAULT 0 CHECK (calories_approx >= 0),")
    w("    allergen_info TEXT,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
    w(");")
    w("")
    w("COMMENT ON TABLE products IS 'Sản phẩm cơ sở trong danh mục toàn chuỗi (Master Product Catalog)';")
    w("")
    w("-- BẢNG 10: product_sizes (Biến thể kích cỡ của món ăn)")
    w("CREATE TABLE IF NOT EXISTS product_sizes (")
    w("    size_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    product_id UUID NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,")
    w("    size_name VARCHAR(50) NOT NULL,")
    w("    price_adjustment DECIMAL(12,0) NOT NULL DEFAULT 0 CHECK (price_adjustment >= 0),")
    w("    display_order INT NOT NULL DEFAULT 0,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    CONSTRAINT uq_product_size_name UNIQUE (product_id, size_name)")
    w(");")
    w("")
    w("COMMENT ON TABLE product_sizes IS 'Các tùy chọn kích cỡ (Size S, Size M, Size L, Standard) và phụ thu tương ứng';")
    w("")
    w("-- BẢNG 11: product_branch_prices (Bảng giá vùng & Khóa món 86 theo chi nhánh)")
    w("CREATE TABLE IF NOT EXISTS product_branch_prices (")
    w("    branch_price_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    product_id UUID NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,")
    w("    branch_id UUID NOT NULL REFERENCES branches(branch_id) ON DELETE CASCADE,")
    w("    price_override DECIMAL(12,0) NOT NULL CHECK (price_override >= 0),")
    w("    is_available_86 BOOLEAN NOT NULL DEFAULT TRUE,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    CONSTRAINT uq_branch_product_override UNIQUE (branch_id, product_id)")
    w(");")
    w("")
    w("COMMENT ON TABLE product_branch_prices IS 'Thiết lập giá bán đặc thù theo vùng địa lý và bật/tắt trạng thái hết hàng 86-Toggle';")
    w("")
    w("-- BẢNG 12: modifiers (Tùy chọn bổ sung: Đường, Đá, Topping, Sữa)")
    w("CREATE TABLE IF NOT EXISTS modifiers (")
    w("    modifier_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    code VARCHAR(50) NOT NULL UNIQUE,")
    w("    name VARCHAR(100) NOT NULL,")
    w("    type modifier_type_enum NOT NULL,")
    w("    extra_price DECIMAL(12,0) NOT NULL DEFAULT 0 CHECK (extra_price >= 0),")
    w("    is_available BOOLEAN NOT NULL DEFAULT TRUE,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE modifiers IS 'Danh mục các tùy chọn đường, đá, topping và sữa hạt thêm';")
    w("")
    w("-- BẢNG 13: product_modifiers (Bảng liên kết Món ăn - Tùy chọn Modifiers)")
    w("CREATE TABLE IF NOT EXISTS product_modifiers (")
    w("    product_id UUID NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,")
    w("    modifier_id UUID NOT NULL REFERENCES modifiers(modifier_id) ON DELETE CASCADE,")
    w("    is_default BOOLEAN NOT NULL DEFAULT FALSE,")
    w("    max_quantity INT NOT NULL DEFAULT 1 CHECK (max_quantity >= 1),")
    w("    PRIMARY KEY (product_id, modifier_id)")
    w(");")
    w("")
    w("COMMENT ON TABLE product_modifiers IS 'Quy định các loại topping/tùy biến được phép áp dụng cho từng món ăn';")
    w("")
    w("-- ============================================================================")
    w("-- 2.5 NHÓM 4: NGUYÊN VẬT LIỆU THÔ, ĐỊNH MỨC BOM & KIỂM KÊ KHO")
    w("-- ============================================================================")
    w("")
    w("-- BẢNG 14: ingredients (Danh mục nguyên vật liệu thô)")
    w("CREATE TABLE IF NOT EXISTS ingredients (")
    w("    ingredient_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    code VARCHAR(50) NOT NULL UNIQUE,")
    w("    name VARCHAR(150) NOT NULL,")
    w("    unit VARCHAR(20) NOT NULL CHECK (unit IN ('ml', 'g', 'piece', 'can', 'pack')),")
    w("    current_stock DECIMAL(10,3) NOT NULL DEFAULT 0 CHECK (current_stock >= 0),")
    w("    min_stock_threshold DECIMAL(10,3) NOT NULL DEFAULT 0 CHECK (min_stock_threshold >= 0),")
    w("    unit_cost DECIMAL(12,0) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
    w(");")
    w("")
    w("COMMENT ON TABLE ingredients IS 'Nguyên vật liệu thô (Cốt trà, Hạt cà phê, Sữa đặc, Bột béo, Ly giấy, Ống hút)';")
    w("")
    w("-- BẢNG 15: recipes_bom (Công thức định mức nguyên vật liệu tiêu chuẩn)")
    w("CREATE TABLE IF NOT EXISTS recipes_bom (")
    w("    recipe_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    product_id UUID NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,")
    w("    size_id UUID NOT NULL REFERENCES product_sizes(size_id) ON DELETE CASCADE,")
    w("    ingredient_id UUID NOT NULL REFERENCES ingredients(ingredient_id) ON DELETE RESTRICT,")
    w("    standard_quantity DECIMAL(10,3) NOT NULL CHECK (standard_quantity > 0),")
    w("    wastage_percentage DECIMAL(5,2) NOT NULL DEFAULT 0 CHECK (wastage_percentage >= 0),")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    CONSTRAINT uq_product_size_ingredient UNIQUE (product_id, size_id, ingredient_id)")
    w(");")
    w("")
    w("COMMENT ON TABLE recipes_bom IS 'Định mức Bill of Materials (BOM) chuẩn làm căn cứ tự động trừ kho và tính COGS';")
    w("")
    w("-- BẢNG 16: inventory_checks (Phiếu kiểm kê tồn kho định kỳ)")
    w("CREATE TABLE IF NOT EXISTS inventory_checks (")
    w("    check_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    branch_id UUID NOT NULL REFERENCES branches(branch_id) ON DELETE RESTRICT,")
    w("    checked_by UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,")
    w("    approved_by UUID REFERENCES users(user_id) ON DELETE SET NULL,")
    w("    check_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    status inventory_check_status_enum NOT NULL DEFAULT 'Draft',")
    w("    notes TEXT,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE inventory_checks IS 'Phiếu kiểm kê kho vật lý định kỳ theo ca/ngày tại từng chi nhánh';")
    w("")
    w("-- BẢNG 17: inventory_check_details (Chi tiết số lượng kiểm kê từng nguyên liệu)")
    w("CREATE TABLE IF NOT EXISTS inventory_check_details (")
    w("    detail_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    check_id UUID NOT NULL REFERENCES inventory_checks(check_id) ON DELETE CASCADE,")
    w("    ingredient_id UUID NOT NULL REFERENCES ingredients(ingredient_id) ON DELETE RESTRICT,")
    w("    system_quantity DECIMAL(10,3) NOT NULL CHECK (system_quantity >= 0),")
    w("    actual_quantity DECIMAL(10,3) NOT NULL CHECK (actual_quantity >= 0),")
    w("    difference_quantity DECIMAL(10,3) NOT NULL,")
    w("    reason TEXT,")
    w("    PRIMARY KEY (detail_id),")
    w("    CONSTRAINT uq_check_ingredient UNIQUE (check_id, ingredient_id)")
    w(");")
    w("")
    w("COMMENT ON TABLE inventory_check_details IS 'Chi tiết chênh lệch tồn kho thực tế so với số liệu sổ sách hệ thống';")
    w("")
    w("-- ============================================================================")
    w("-- 2.6 NHÓM 5: ĐƠN HÀNG ĐA KÊNH, CHI TIẾT MÓN & THANH TOÁN VIETQR / TIỀN MẶT")
    w("-- ============================================================================")
    w("")
    w("-- BẢNG 18: customers (Hồ sơ khách hàng CRM)")
    w("CREATE TABLE IF NOT EXISTS customers (")
    w("    customer_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    phone_number VARCHAR(20) NOT NULL UNIQUE,")
    w("    full_name VARCHAR(150),")
    w("    email VARCHAR(150),")
    w("    birth_date DATE,")
    w("    membership_tier VARCHAR(50) NOT NULL DEFAULT 'Standard' CHECK (membership_tier IN ('Standard', 'Silver', 'Gold', 'Diamond')),")
    w("    cup_balance INT NOT NULL DEFAULT 0 CHECK (cup_balance >= 0),")
    w("    total_points INT NOT NULL DEFAULT 0 CHECK (total_points >= 0),")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    last_visited_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    is_deleted BOOLEAN NOT NULL DEFAULT FALSE")
    w(");")
    w("")
    w("COMMENT ON TABLE customers IS 'Hồ sơ thành viên CRM, quỹ ly tích lũy Takeaway và điểm thưởng';")
    w("")
    w("-- BẢNG 19: orders (Đơn hàng tổng hợp 3 kênh: DineIn, TakeAway, Delivery)")
    w("CREATE TABLE IF NOT EXISTS orders (")
    w("    order_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    branch_id UUID NOT NULL REFERENCES branches(branch_id) ON DELETE RESTRICT,")
    w("    table_id UUID REFERENCES tables(table_id) ON DELETE SET NULL,")
    w("    customer_id UUID REFERENCES customers(customer_id) ON DELETE SET NULL,")
    w("    order_code VARCHAR(50) NOT NULL UNIQUE,")
    w("    order_type order_type_enum NOT NULL,")
    w("    status order_status_enum NOT NULL DEFAULT 'PendingPayment',")
    w("    sub_total DECIMAL(12,0) NOT NULL CHECK (sub_total >= 0),")
    w("    discount_amount DECIMAL(12,0) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),")
    w("    delivery_fee DECIMAL(12,0) NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),")
    w("    total_amount DECIMAL(12,0) NOT NULL CHECK (total_amount >= 0),")
    w("    delivery_address VARCHAR(500),")
    w("    recipient_name VARCHAR(150),")
    w("    recipient_phone VARCHAR(20),")
    w("    delivery_notes TEXT,")
    w("    expires_at TIMESTAMPTZ,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    paid_at TIMESTAMPTZ,")
    w("    completed_at TIMESTAMPTZ")
    w(");")
    w("")
    w("COMMENT ON TABLE orders IS 'Đơn hàng tổng hợp đa kênh hỗ trợ Dine-In 2 nhánh, Delivery phí 20k và Takeaway POS';")
    w("COMMENT ON COLUMN orders.delivery_fee IS 'Phí ship cố định 20.000 VNĐ cho Delivery, 0 VNĐ cho Dine-In và Takeaway';")
    w("COMMENT ON COLUMN orders.expires_at IS 'Thời điểm hết hạn thanh toán (TTL 10 phút cho đơn VietQR)';")
    w("")
    w("-- BẢNG 20: order_items (Chi tiết món ăn trong đơn hàng)")
    w("CREATE TABLE IF NOT EXISTS order_items (")
    w("    order_item_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    order_id UUID NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,")
    w("    product_id UUID NOT NULL REFERENCES products(product_id) ON DELETE RESTRICT,")
    w("    size_id UUID NOT NULL REFERENCES product_sizes(size_id) ON DELETE RESTRICT,")
    w("    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),")
    w("    unit_price DECIMAL(12,0) NOT NULL CHECK (unit_price >= 0),")
    w("    subtotal_price DECIMAL(12,0) NOT NULL CHECK (subtotal_price >= 0),")
    w("    note VARCHAR(255),")
    w("    item_status VARCHAR(50) NOT NULL DEFAULT 'Pending' CHECK (item_status IN ('Pending', 'Preparing', 'Ready', 'Served', 'Cancelled')),")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE order_items IS 'Chi tiết các món ăn, kích cỡ và số lượng trong từng đơn hàng';")
    w("")
    w("-- BẢNG 21: order_item_modifiers (Tùy chọn topping đi kèm món trong đơn)")
    w("CREATE TABLE IF NOT EXISTS order_item_modifiers (")
    w("    item_mod_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    order_item_id UUID NOT NULL REFERENCES order_items(order_item_id) ON DELETE CASCADE,")
    w("    modifier_id UUID NOT NULL REFERENCES modifiers(modifier_id) ON DELETE RESTRICT,")
    w("    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),")
    w("    extra_price DECIMAL(12,0) NOT NULL DEFAULT 0 CHECK (extra_price >= 0),")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE order_item_modifiers IS 'Chi tiết các tùy biến đường, đá, topping được chọn cho từng món';")
    w("")
    w("-- BẢNG 22: payments (Giao dịch thanh toán đơn hàng)")
    w("CREATE TABLE IF NOT EXISTS payments (")
    w("    payment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    order_id UUID NOT NULL REFERENCES orders(order_id) ON DELETE RESTRICT,")
    w("    payment_method payment_method_enum NOT NULL,")
    w("    amount DECIMAL(12,0) NOT NULL CHECK (amount >= 0),")
    w("    transaction_code VARCHAR(100) UNIQUE,")
    w("    status payment_status_enum NOT NULL DEFAULT 'Pending',")
    w("    payos_payment_link_id VARCHAR(100),")
    w("    paid_at TIMESTAMPTZ,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE payments IS 'Nhật ký giao dịch thanh toán chuyển khoản VietQR PayOS hoặc Tiền mặt';")
    w("")
    w("-- ============================================================================")
    w("-- 2.7 NHÓM 6: CRM KHÁCH HÀNG, SỔ CÁI TÍCH 10 LY TAKEAWAY, VOUCHERS & ĐÁNH GIÁ")
    w("-- ============================================================================")
    w("")
    w("-- BẢNG 23: loyalty_cup_transactions (Nhật ký tích/đổi 10 ly Takeaway)")
    w("CREATE TABLE IF NOT EXISTS loyalty_cup_transactions (")
    w("    trans_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    customer_id UUID NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,")
    w("    order_id UUID REFERENCES orders(order_id) ON DELETE SET NULL,")
    w("    cups_earned INT NOT NULL DEFAULT 0 CHECK (cups_earned >= 0),")
    w("    cups_redeemed INT NOT NULL DEFAULT 0 CHECK (cups_redeemed >= 0),")
    w("    transaction_type loyalty_transaction_type_enum NOT NULL,")
    w("    notes VARCHAR(255),")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE loyalty_cup_transactions IS 'Lưu vết lịch sử tích lũy 10 ly tặng 1 ly cho kênh Takeaway';")
    w("")
    w("-- BẢNG 24: vouchers (Mã giảm giá và khuyến mãi)")
    w("CREATE TABLE IF NOT EXISTS vouchers (")
    w("    voucher_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    code VARCHAR(50) NOT NULL UNIQUE,")
    w("    discount_type voucher_discount_type_enum NOT NULL,")
    w("    discount_value DECIMAL(12,2) NOT NULL CHECK (discount_value > 0),")
    w("    min_order_value DECIMAL(12,0) NOT NULL DEFAULT 0 CHECK (min_order_value >= 0),")
    w("    max_discount_amount DECIMAL(12,0) CHECK (max_discount_amount >= 0),")
    w("    start_date TIMESTAMPTZ NOT NULL,")
    w("    end_date TIMESTAMPTZ NOT NULL,")
    w("    usage_limit INT NOT NULL DEFAULT 1000 CHECK (usage_limit >= 0),")
    w("    used_count INT NOT NULL DEFAULT 0 CHECK (used_count >= 0),")
    w("    is_active BOOLEAN NOT NULL DEFAULT TRUE,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,")
    w("    CONSTRAINT ck_voucher_dates CHECK (end_date > start_date)")
    w(");")
    w("")
    w("COMMENT ON TABLE vouchers IS 'Mã ưu đãi giảm giá toàn chuỗi hoặc theo chiến dịch marketing';")
    w("")
    w("-- BẢNG 25: customer_reviews (Đánh giá 1-5 sao và ảnh phản hồi)")
    w("CREATE TABLE IF NOT EXISTS customer_reviews (")
    w("    review_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    order_id UUID NOT NULL REFERENCES orders(order_id) ON DELETE RESTRICT,")
    w("    product_id UUID REFERENCES products(product_id) ON DELETE SET NULL,")
    w("    customer_id UUID REFERENCES customers(customer_id) ON DELETE SET NULL,")
    w("    rating_stars INT NOT NULL CHECK (rating_stars BETWEEN 1 AND 5),")
    w("    comment TEXT,")
    w("    photo_urls JSONB,")
    w("    is_anonymous BOOLEAN NOT NULL DEFAULT FALSE,")
    w("    is_approved BOOLEAN NOT NULL DEFAULT FALSE,")
    w("    is_urgent_alert BOOLEAN NOT NULL DEFAULT FALSE,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE customer_reviews IS 'Đánh giá chất lượng món ăn và phục vụ (tự động bật is_urgent_alert nếu <= 2 sao)';")
    w("")
    w("-- BẢNG 26: combos (AI-2 Gợi ý Combo thông minh qua luật kết hợp Apriori)")
    w("CREATE TABLE IF NOT EXISTS combos (")
    w("    combo_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    code VARCHAR(50) NOT NULL UNIQUE,")
    w("    name VARCHAR(150) NOT NULL,")
    w("    description TEXT,")
    w("    discount_percentage DECIMAL(5,2) NOT NULL DEFAULT 10.00 CHECK (discount_percentage >= 0),")
    w("    support_metric DECIMAL(6,4),")
    w("    confidence_metric DECIMAL(6,4),")
    w("    lift_metric DECIMAL(6,4),")
    w("    is_active BOOLEAN NOT NULL DEFAULT TRUE,")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE combos IS 'Danh mục combo món được AI Apriori đề xuất dựa trên phân tích giỏ hàng lịch sử';")
    w("")
    w("-- BẢNG 27: combo_items (Các món ăn thành phần trong combo)")
    w("CREATE TABLE IF NOT EXISTS combo_items (")
    w("    combo_item_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    combo_id UUID NOT NULL REFERENCES combos(combo_id) ON DELETE CASCADE,")
    w("    product_id UUID NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,")
    w("    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),")
    w("    PRIMARY KEY (combo_item_id),")
    w("    CONSTRAINT uq_combo_product UNIQUE (combo_id, product_id)")
    w(");")
    w("")
    w("COMMENT ON TABLE combo_items IS 'Chi tiết các sản phẩm cấu thành combo khuyến mãi';")
    w("")
    w("-- ============================================================================")
    w("-- 2.8 NHÓM 7: QUẢN LÝ CA KÉT TIỀN, ĐỐI SOÁT Z-REPORT & CHẤM CÔNG KHÓA WIFI")
    w("-- ============================================================================")
    w("")
    w("-- BẢNG 28: shifts (Ca làm việc két tiền và đối soát Z-Report)")
    w("CREATE TABLE IF NOT EXISTS shifts (")
    w("    shift_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    branch_id UUID NOT NULL REFERENCES branches(branch_id) ON DELETE RESTRICT,")
    w("    cashier_id UUID NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,")
    w("    opening_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    closing_time TIMESTAMPTZ,")
    w("    initial_cash DECIMAL(12,0) NOT NULL CHECK (initial_cash >= 0),")
    w("    actual_cash_counted DECIMAL(12,0) CHECK (actual_cash_counted >= 0),")
    w("    system_cash_calculated DECIMAL(12,0) DEFAULT 0,")
    w("    cash_difference DECIMAL(12,0) DEFAULT 0,")
    w("    shift_notes TEXT,")
    w("    status shift_status_enum NOT NULL DEFAULT 'Open',")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE shifts IS 'Quản lý ca két tiền mặt thu ngân và đối soát biên bản Z-Report cuối ca';")
    w("")
    w("-- BẢNG 29: attendances (Nhật ký chấm công khóa mạng WiFi chi nhánh)")
    w("CREATE TABLE IF NOT EXISTS attendances (")
    w("    attendance_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),")
    w("    branch_id UUID NOT NULL REFERENCES branches(branch_id) ON DELETE RESTRICT,")
    w("    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,")
    w("    employee_code VARCHAR(50) NOT NULL,")
    w("    check_in_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,")
    w("    check_out_time TIMESTAMPTZ,")
    w("    verified_ip VARCHAR(50) NOT NULL,")
    w("    verified_bssid VARCHAR(50) NOT NULL,")
    w("    status attendance_status_enum NOT NULL DEFAULT 'OnTime',")
    w("    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP")
    w(");")
    w("")
    w("COMMENT ON TABLE attendances IS 'Nhật ký chấm công vào ca/ra ca xác thực kép qua BSSID/IP Subnet WiFi chi nhánh';")
    w("")
    w("-- ============================================================================")
    w("-- 2.9 CHIẾN LƯỢC ĐÁNH CHỈ MỤC HIỆU NĂNG CAO (INDEXING STRATEGY)")
    w("-- ============================================================================")
    w("")
    w("-- B-Tree Composite Indexes cho Thực đơn & Bảng giá vùng")
    w("CREATE INDEX IF NOT EXISTS idx_products_category_active ")
    w("ON products (category_id, is_available) ")
    w("WHERE is_deleted = FALSE;")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_branch_prices_lookup ")
    w("ON product_branch_prices (branch_id, product_id, is_available_86);")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_product_sizes_prod_order ")
    w("ON product_sizes (product_id, display_order);")
    w("")
    w("-- B-Tree Composite Indexes cho Hàng đợi Bếp KDS & Đơn hàng")
    w("CREATE INDEX IF NOT EXISTS idx_orders_branch_status_created ")
    w("ON orders (branch_id, status, created_at);")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_orders_customer_history ")
    w("ON orders (customer_id, created_at DESC);")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_order_items_order_status ")
    w("ON order_items (order_id, item_status);")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_payments_order_status ")
    w("ON payments (order_id, status);")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_payments_transaction_code ")
    w("ON payments (transaction_code) ")
    w("WHERE transaction_code IS NOT NULL;")
    w("")
    w("-- B-Tree Composite Indexes cho CRM & Sổ cái Tích ly")
    w("CREATE INDEX IF NOT EXISTS idx_customers_phone ")
    w("ON customers (phone_number);")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_loyalty_cust_created ")
    w("ON loyalty_cup_transactions (customer_id, created_at DESC);")
    w("")
    w("-- B-Tree Composite Indexes cho Chấm công & Ca két")
    w("CREATE INDEX IF NOT EXISTS idx_attendances_branch_user_date ")
    w("ON attendances (branch_id, user_id, check_in_time DESC);")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_shifts_branch_status ")
    w("ON shifts (branch_id, status, opening_time DESC);")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_wifi_configs_branch_active ")
    w("ON branch_wifi_configs (branch_id) ")
    w("WHERE is_active = TRUE;")
    w("")
    w("-- GIN Indexes cho Full-Text Search, JSONB Audit Logs & Photos")
    w("CREATE INDEX IF NOT EXISTS idx_products_fts_name ")
    w("ON products USING GIN (to_tsvector('simple', name));")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_audit_logs_jsonb ")
    w("ON audit_logs USING GIN (new_values);")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_reviews_photos_jsonb ")
    w("ON customer_reviews USING GIN (photo_urls);")
    w("")
    w("CREATE INDEX IF NOT EXISTS idx_reviews_urgent_alerts ")
    w("ON customer_reviews (rating_stars, created_at DESC) ")
    w("WHERE is_urgent_alert = TRUE;")
    w("")
    w("-- ============================================================================")
    w("-- 2.10 HÀM TỰ ĐỘNG HÓA & DATABASE TRIGGERS")
    w("-- ============================================================================")
    w("")
    w("CREATE OR REPLACE FUNCTION trigger_set_updated_at()")
    w("RETURNS TRIGGER AS $$")
    w("BEGIN")
    w("    NEW.updated_at = CURRENT_TIMESTAMP;")
    w("    RETURN NEW;")
    w("END;")
    w("$$ LANGUAGE plpgsql;")
    w("")
    w("DROP TRIGGER IF EXISTS trg_branches_updated_at ON branches;")
    w("CREATE TRIGGER trg_branches_updated_at")
    w("BEFORE UPDATE ON branches")
    w("FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();")
    w("")
    w("DROP TRIGGER IF EXISTS trg_categories_updated_at ON categories;")
    w("CREATE TRIGGER trg_categories_updated_at")
    w("BEFORE UPDATE ON categories")
    w("FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();")
    w("")
    w("DROP TRIGGER IF EXISTS trg_products_updated_at ON products;")
    w("CREATE TRIGGER trg_products_updated_at")
    w("BEFORE UPDATE ON products")
    w("FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();")
    w("")
    w("DROP TRIGGER IF EXISTS trg_ingredients_updated_at ON ingredients;")
    w("CREATE TRIGGER trg_ingredients_updated_at")
    w("BEFORE UPDATE ON ingredients")
    w("FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();")
    w("")
    w("DROP TRIGGER IF EXISTS trg_recipes_bom_updated_at ON recipes_bom;")
    w("CREATE TRIGGER trg_recipes_bom_updated_at")
    w("BEFORE UPDATE ON recipes_bom")
    w("FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();")
    w("")
    w("DROP TRIGGER IF EXISTS trg_vouchers_updated_at ON vouchers;")
    w("CREATE TRIGGER trg_vouchers_updated_at")
    w("BEFORE UPDATE ON vouchers")
    w("FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();")
    w("")
    w("DROP TRIGGER IF EXISTS trg_tables_updated_at ON tables;")
    w("CREATE TRIGGER trg_tables_updated_at")
    w("BEFORE UPDATE ON tables")
    w("FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();")
    w("")
    w("DROP TRIGGER IF EXISTS trg_combos_updated_at ON combos;")
    w("CREATE TRIGGER trg_combos_updated_at")
    w("BEFORE UPDATE ON combos")
    w("FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();")
    w("")
    w("CREATE OR REPLACE FUNCTION trigger_set_urgent_review_alert()")
    w("RETURNS TRIGGER AS $$")
    w("BEGIN")
    w("    IF NEW.rating_stars <= 2 THEN")
    w("        NEW.is_urgent_alert = TRUE;")
    w("    ELSE")
    w("        NEW.is_urgent_alert = FALSE;")
    w("    END IF;")
    w("    RETURN NEW;")
    w("END;")
    w("$$ LANGUAGE plpgsql;")
    w("")
    w("DROP TRIGGER IF EXISTS trg_customer_reviews_urgent_alert ON customer_reviews;")
    w("CREATE TRIGGER trg_customer_reviews_urgent_alert")
    w("BEFORE INSERT OR UPDATE ON customer_reviews")
    w("FOR EACH ROW EXECUTE FUNCTION trigger_set_urgent_review_alert();")
    w("```")
    w("")
    w("---")
    w("")
    return "\n".join(lines)

print("Part 2 module loaded")
