# doc_sections_part1.py - Chapter 1: Overview & Architecture

def get_part1():
    lines = []
    w = lines.append

    w("# 💾 TÀI LIỆU THIẾT KẾ CƠ SỞ DỮ LIỆU & BỘ KỊCH BẢN DỮ LIỆU MẪU (DATABASE DDL & SEED DATA SPECIFICATION)")
    w("## HỆ THỐNG QUẢN LÝ VÀ VẬN HÀNH QUÁN CÀ PHÊ THÔNG MINH SMART F&B OS (v2.5.0)")
    w("")
    w("> [!IMPORTANT]")
    w("> **Mã tài liệu:** `SPEC-DB-SEED-01` | **Phiên bản:** `v2.5.0-Production-Ready`  ")
    w("> **Hệ quản trị CSDL đích:** PostgreSQL 16 Enterprise Relational Database Engine  ")
    w("> **Framework truy cập dữ liệu:** Entity Framework Core 8 (.NET 8 Clean Architecture) & Dapper High-Throughput  ")
    w("> **Chuẩn mực thiết kế:** 100% Chuẩn hóa 3NF (Third Normal Form), Khóa chính UUID v4 (`gen_random_uuid()`), Toàn vẹn tham chiếu (Foreign Keys & Cascade Rules), Ràng buộc kiểm tra (Check Constraints), Bộ chỉ mục kép B-Tree/GIN, Triggers tự động hóa, Sổ cái bất biến Audit Trail, và **ZERO Hardcoded Placeholders / Zero Ellipses (`...`)**.")
    w("")
    w("---")
    w("")
    w("## 📑 MỤC LỤC TOÀN DIỆN")
    w("")
    w("1. [CHƯƠNG 1: TỔNG QUAN KIẾN TRÚC DỮ LIỆU & NGUYÊN TẮC THIẾT KẾ 3NF](#chương-1-tổng-quan-kiến-trúc-dữ-liệu--nguyên-tắc-thiết-kế-3nf)")
    w("   - 1.1 [Khái quát hệ thống & 5 Trụ cột nghiệp vụ cốt lõi v2.5.0](#11-khái-quát-hệ-thống--5-trụ-cột-nghiệp-vụ-cốt-lõi-v250)")
    w("   - 1.2 [Ma trận 27 Thực thể Dữ liệu Chuẩn hóa 3NF (Phân hệ 1 đến 8)](#12-ma-trận-27-thực-thể-dữ-liệu-chuẩn-hóa-3nf-phân-hệ-1-đến-8)")
    w("   - 1.3 [Quy ước kiểu dữ liệu, tiền tệ và định lượng chính xác](#13-quy-ước-kiểu-dữ-liệu-tiền-tệ-và-định-lượng-chính-xác)")
    w("   - 1.4 [Hướng dẫn thực thi kịch bản (psql CLI, Docker Container & EF Core Code-First)](#14-hướng-dẫn-thực-thi-kịch-bản-psql-cli-docker-container--ef-core-code-first)")
    w("2. [CHƯƠNG 2: PHẦN I — TOÀN VĂN KỊCH BẢN DDL POSTGRESQL 16 (FULL SCHEMA SCRIPT)](#chương-2-phần-i--toàn-văn-kịch-bản-ddl-postgresql-16-full-schema-script)")
    w("   - 2.1 [Khởi tạo Extensions & Các kiểu dữ liệu liệt kê (ENUMs)](#21-khởi-tạo-extensions--các-kiểu-dữ-liệu-liệt-kê-enums)")
    w("   - 2.2 [Nhóm 1: Hệ thống, Cơ sở Chi nhánh & Bàn phục vụ QR](#22-nhóm-1-hệ-thống-cơ-sở-chi-nhánh--bàn-phục-vụ-qr)")
    w("   - 2.3 [Nhóm 2: Người dùng, Phân quyền RBAC & Nhật ký kiểm toán](#23-nhóm-2-người-dùng-phân-quyền-rbac--nhật-ký-kiểm-toán)")
    w("   - 2.4 [Nhóm 3: Thực đơn, Biến thể kích cỡ, Bảng giá vùng & Tùy chọn Modifiers](#24-nhóm-3-thực-đơn-biến-thể-kích-cỡ-bảng-giá-vùng--tùy-chọn-modifiers)")
    w("   - 2.5 [Nhóm 4: Nguyên vật liệu thô, Định mức BOM & Kiểm kê kho](#25-nhóm-4-nguyên-vật-liệu-thô-định-mức-bom--kiểm-kê-kho)")
    w("   - 2.6 [Nhóm 5: Đơn hàng đa kênh, Chi tiết món & Thanh toán VietQR / Tiền mặt](#26-nhóm-5-đơn-hàng-đa-kênh-chi-tiết-món--thanh-toán-vietqr--tiền-mặt)")
    w("   - 2.7 [Nhóm 6: CRM Khách hàng, Sổ cái tích 10 ly Takeaway, Vouchers & Đánh giá](#27-nhóm-6-crm-khách-hàng-sổ-cái-tích-10-ly-takeaway-vouchers--đánh-giá)")
    w("   - 2.8 [Nhóm 7: Quản lý Ca két tiền, Đối soát Z-Report & Chấm công khóa WiFi](#28-nhóm-7-quản-lý-ca-két-tiền-đối-soát-z-report--chấm-công-khóa-wifi)")
    w("   - 2.9 [Chiến lược Đánh chỉ mục hiệu năng cao (Composite B-Tree & GIN Indexes)](#29-chiến-lược-đánh-chỉ-mục-hiệu-năng-cao-composite-b-tree--gin-indexes)")
    w("   - 2.10 [Hàm tự động hóa & Database Triggers (`updated_at` & Alert <= 2 Sao)](#210-hàm-tự-động-hóa--database-triggers-updated_at--alert--2-sao)")
    w("3. [CHƯƠNG 3: PHẦN II — TOÀN VĂN KỊCH BẢN DML SEED DATA THỰC TẾ 100% (ZERO PLACEHOLDERS)](#chương-3-phần-ii--toàn-văn-kịch-bản-dml-seed-data-thực-tế-100-zero-placeholders)")
    w("   - 3.1 [Dữ liệu 3 Chi nhánh đại diện 3 miền & Cấu hình WiFi BSSID/Subnet](#31-dữ-liệu-3-chi-nhánh-đại-diện-3-miền--cấu-hình-wifi-bssidsubnet)")
    w("   - 3.2 [Dữ liệu Sơ đồ 30 Bàn phục vụ (10 bàn/chi nhánh) với mã QR Token](#32-dữ-liệu-sơ-đồ-30-bàn-phục-vụ-10-bànchi-nhánh-với-mã-qr-token)")
    w("   - 3.3 [Dữ liệu 10 Tài khoản Người dùng & Phân quyền RBAC (BCrypt Hash)](#33-dữ-liệu-10-tài-khoản-người-dùng--phân-quyền-rbac-bcrypt-hash)")
    w("   - 3.4 [Dữ liệu 5 Danh mục Thực đơn (Master Categories)](#34-dữ-liệu-5-danh-mục-thực-đơn-master-categories)")
    w("   - 3.5 [Dữ liệu 22 Món ăn / Đồ uống cơ sở (Master Products)](#35-dữ-liệu-22-món-ăn--đồ-uống-cơ-sở-master-products)")
    w("   - 3.6 [Dữ liệu Biến thể Kích cỡ Món ăn (`product_sizes`)](#36-dữ-liệu-biến-thể-kích-cỡ-món-ăn-product_sizes)")
    w("   - 3.7 [Dữ liệu Bảng giá vùng & Khóa món 86-Toggle theo chi nhánh (`product_branch_prices`)](#37-dữ-liệu-bảng-giá-vùng--khóa-món-86-toggle-theo-chi-nhánh-product_branch_prices)")
    w("   - 3.8 [Dữ liệu Tùy chọn Modifiers (Đường, Đá, Topping, Sữa) & Ma trận Liên kết](#38-dữ-liệu-tùy-chọn-modifiers-đường-đá-topping-sữa--ma-trận-liên-kết)")
    w("   - 3.9 [Dữ liệu 15 Nguyên vật liệu thô & Công thức định mức BOM chuẩn (`recipes_bom`)](#39-dữ-liệu-15-nguyên-vật-liệu-thô--công-thức-định-mức-bom-chuẩn-recipes_bom)")
    w("   - 3.10 [Dữ liệu 10 Hồ sơ Khách hàng CRM & Tiến trình Quỹ ly (0 đến 18 ly)](#310-dữ-liệu-10-hồ-sơ-khách-hàng-crm--tiến-trình-quỹ-ly-0-đến-18-ly)")
    w("   - 3.11 [Dữ liệu 6 Đơn hàng mẫu đại diện đa kênh & Giao dịch thanh toán đầy đủ](#311-dữ-liệu-6-đơn-hàng-mẫu-đại-diện-đa-kênh--giao-dịch-thanh-toán-đầy-đủ)")
    w("   - 3.12 [Dữ liệu Ca làm việc két tiền & Đối soát Z-Report (Khớp tiền & Lệch két +70k)](#312-dữ-liệu-ca-làm-việc-két-tiền--đối-soát-z-report-khớp-tiền--lệch-két-70k)")
    w("   - 3.13 [Dữ liệu Chấm công xác thực kép WiFi BSSID/IP Subnet](#313-dữ-liệu-chấm-công-xác-thực-kép-wifi-bssidip-subnet)")
    w("   - 3.14 [Dữ liệu Kiểm kê kho định kỳ & Đối chiếu hao hụt thực tế](#314-dữ-liệu-kiểm-kê-kho-định-kỳ--đối-chiếu-hao-hụt-thực-tế)")
    w("   - 3.15 [Dữ liệu Mã khuyến mãi Voucher giảm giá](#315-dữ-liệu-mã-khuyến-mãi-voucher-giảm-giá)")
    w("   - 3.16 [Dữ liệu Đánh giá phản hồi khách hàng (Kèm URL ảnh & Cảnh báo đỏ 2 sao)](#316-dữ-liệu-đánh-giá-phản-hồi-khách-hàng-kèm-url-ảnh--cảnh-báo-đỏ-2-sao)")
    w("   - 3.17 [Dữ liệu Gợi ý Combo thông minh AI Apriori (`combos` & `combo_items`)](#317-dữ-liệu-gợi-ý-combo-thông-minh-ai-apriori-combos--combo_items)")
    w("   - 3.18 [Dữ liệu Nhật ký kiểm toán hệ thống mẫu (`audit_logs`)](#318-dữ-liệu-nhật-ký-kiểm-toán-hệ-thống-mẫu-audit_logs)")
    w("4. [CHƯƠNG 4: PHẦN III — HƯỚNG DẪN TÍCH HỢP EF CORE 8 & TRUY VẤN KIỂM CHỨNG TOÀN DIỆN](#chương-4-phần-iii--hướng-dẫn-tích-hợp-ef-core-8--truy-vấn-kiểm-chứng-toàn-diện)")
    w("   - 4.1 [Lớp khởi tạo dữ liệu C# `DbInitializer.cs` (.NET 8 EF Core)](#41-lớp-khởi-tạo-dữ-liệu-c-dbinitializercs-net-8-ef-core)")
    w("   - 4.2 [Bộ 27 Truy vấn SQL Kiểm chứng Toàn vẹn Cơ sở Dữ liệu](#42-bộ-27-truy-vấn-sql-kiểm-chứng-toàn-vẹn-cơ-sở-dữ-liệu)")
    w("   - 4.3 [Checklist nghiệm thu kỹ thuật và lưu ý vận hành Production](#43-checklist-nghiệm-thu-kỹ-thuật-và-lưu-ý-vận-hành-production)")
    w("")
    w("---")
    w("")
    w("# CHƯƠNG 1: TỔNG QUAN KIẾN TRÚC DỮ LIỆU & NGUYÊN TẮC THIẾT KẾ 3NF")
    w("")
    w("## 1.1 Khái quát hệ thống & 5 Trụ cột nghiệp vụ cốt lõi v2.5.0")
    w("")
    w("Hệ thống **Smart F&B Operating System (Smart F&B OS v2.5.0)** là nền tảng quản trị chuỗi nhà hàng - cà phê thông minh đa chi nhánh. Cơ sở dữ liệu của hệ thống được kiến trúc trên nền tảng **PostgreSQL 16 Enterprise**, tuân thủ nghiêm ngặt mô hình chuẩn hóa **Third Normal Form (3NF)** nhằm đảm bảo tính toàn vẹn dữ liệu (Data Integrity), ngăn ngừa dị thường cập nhật (Update Anomalies) và tối ưu hóa tốc độ xử lý giao dịch thời gian thực (OLTP).")
    w("")
    w("Toàn bộ lược đồ cơ sở dữ liệu (Database Schema) và bộ dữ liệu mẫu (Seed Data) được thiết kế xoay quanh **5 Trụ Cột Nghiệp Vụ Cốt Lõi**:")
    w("")
    w("| STT | Trụ Cột Nghiệp Vụ | Đặc Tả Kỹ Thuật & Hành Vi Database |")
    w("| :---: | :--- | :--- |")
    w("| **1** | **Dine-In 2 Nhánh Linh Hoạt** | • **Nhánh A (Trả trước VietQR):** Khách quét QR bàn $\\rightarrow$ Chọn món $\\rightarrow$ Thanh toán VietQR PayOS $\\rightarrow$ Webhook xác nhận `Paid` $\\rightarrow$ Đơn tự động đẩy xuống Màn hình Bếp (KDS) với trạng thái `Preparing`.<br>• **Nhánh B (Trả sau Tiền mặt):** Khách quét QR bàn $\\rightarrow$ Chọn món $\\rightarrow$ Bấm gọi món $\\rightarrow$ Đơn vào KDS ngay lập tức với trạng thái `Confirmed` $\\rightarrow$ Nhân viên pha chế xong in Phiếu thanh toán có QR động $\\rightarrow$ Thu tiền mặt hoặc chuyển khoản tại bàn chuyển sang `Paid`. |")
    w("| **2** | **QR Delivery Trực Tuyến** | • Khách đặt giao hàng qua Web PWA bắt buộc nhập `recipient_name`, `recipient_phone`, `delivery_address`.<br>• Tự động cộng cố định phí ship `delivery_fee = 20.000 VNĐ` vào `total_amount`.<br>• Bắt buộc thanh toán trước 100% qua VietQR PayOS; đơn chỉ đẩy sang KDS khi `payments.status = 'Paid'`. |")
    w("| **3** | **Takeaway Staff POS Loyalty 10 Ly** | • Thu ngân thao tác tại quầy POS Web, tra cứu hồ sơ CRM bằng số điện thoại (`customers.phone_number`).<br>• Tích lũy số ly vào `customers.cup_balance`. Khi đủ $\\ge 10$ ly, khách được quyền đổi 1 ly miễn phí (`cups_redeemed = 10`), hệ thống tự động trừ tiền món tương ứng trong `orders.discount_amount` và ghi nhật ký sổ cái bất biến `loyalty_cup_transactions`.<br>• Hỗ trợ thu tiền mặt tại quầy (`Cash`) hoặc VietQR tĩnh/động tại quầy. |")
    w("| **4** | **Chấm Công Khóa Mạng WiFi Dual-Factor** | • Nhân viên mở Web Chấm công trên thiết bị cá nhân $\\rightarrow$ Client bắt MAC BSSID Access Point và IP Client Gateway $\\rightarrow$ Backend đối soát với bảng `branch_wifi_configs`.<br>• Chỉ cho phép `check_in` / `check_out` thành công khi thiết bị kết nối đúng BSSID và dải IP Subnet CIDR (vd: `192.168.1.0/24`) của chi nhánh được phân công. |")
    w("| **5** | **Hợp Nhất 100% Web Stack (Xóa Mobile App)** | • Loại bỏ hoàn toàn ứng dụng di động native cho nhân viên; 100% phân hệ (KDS Bếp, POS Thu ngân, Barista, Quản lý, Khách hàng) chạy trên trình duyệt Web Responsive PWA.<br>• Tối ưu hóa tải thực đơn $< 50$ms và phản hồi API $< 200$ms thông qua hệ thống Composite B-Tree và GIN Indexes chuyên biệt. |")
    w("")
    w("---")
    w("")
    w("## 1.2 Ma trận 27 Thực thể Dữ liệu Chuẩn hóa 3NF (Phân hệ 1 đến 8)")
    w("")
    w("Lược đồ cơ sở dữ liệu Smart F&B OS v2.5.0 gồm 27 bảng dữ liệu phân bổ trực quan thành 8 module nghiệp vụ:")
    w("")
    w("```")
    w("┌────────────────────────────────────────────────────────────────────────────────────────────────────────┐")
    w("│                        MA TRẬN 27 THỰC THỂ DỮ LIỆU POSTGRESQL 16 (CHUẨN HÓA 3NF)                       │")
    w("├────┬─────────────────────────────┬───────────────────────────┬─────────────────────────────────────────┤")
    w("│ STT│ Tên Bảng (Table Name)       │ Phân Hệ Nghiệp Vụ         │ Trách Nhiệm Dữ Liệu & Ràng Buộc Khóa    │")
    w("├────┼─────────────────────────────┼───────────────────────────┼─────────────────────────────────────────┤")
    w("│ 01 │ branches                    │ 1. Hạ Tầng & Chi Nhánh    │ PK: branch_id, UK: code (3 Chi nhánh)   │")
    w("│ 02 │ branch_wifi_configs         │ 1. Hạ Tầng & Chi Nhánh    │ PK: wifi_config_id, FK: branch_id, CIDR │")
    w("│ 03 │ tables                      │ 1. Hạ Tầng & Chi Nhánh    │ PK: table_id, FK: branch_id, UK: bàn    │")
    w("├────┼─────────────────────────────┼───────────────────────────┼─────────────────────────────────────────┤")
    w("│ 04 │ users                       │ 2. Người Dùng & RBAC      │ PK: user_id, UK: username, FK: branch_id│")
    w("│ 05 │ roles                       │ 2. Người Dùng & RBAC      │ PK: role_id, UK: role_name (5 Vai trò)  │")
    w("│ 06 │ user_roles                  │ 2. Người Dùng & RBAC      │ PK,FK: (user_id, role_id)               │")
    w("│ 07 │ audit_logs                  │ 2. Người Dùng & RBAC      │ PK: audit_id, FK: user_id, JSONB Diff   │")
    w("├────┼─────────────────────────────┼───────────────────────────┼─────────────────────────────────────────┤")
    w("│ 08 │ categories                  │ 3. Thực Đơn & Biến Thể    │ PK: category_id, UK: name/display_order │")
    w("│ 09 │ products                    │ 3. Thực Đơn & Biến Thể    │ PK: product_id, FK: category_id, UK: sku│")
    w("│ 10 │ product_sizes               │ 3. Thực Đơn & Biến Thể    │ PK: size_id, FK: product_id, UK: size   │")
    w("│ 11 │ product_branch_prices       │ 3. Thực Đơn & Biến Thể    │ PK: branch_price_id, FKs, Khóa 86-Toggle│")
    w("│ 12 │ modifiers                   │ 3. Thực Đơn & Biến Thể    │ PK: modifier_id, UK: name, Đường/Đá/Top │")
    w("│ 13 │ product_modifiers           │ 3. Thực Đơn & Biến Thể    │ PK,FK: (product_id, modifier_id)        │")
    w("├────┼─────────────────────────────┼───────────────────────────┼─────────────────────────────────────────┤")
    w("│ 14 │ ingredients                 │ 4. Nguyên Liệu & Kho BOM  │ PK: ingredient_id, UK: code, Đơn vị g/ml│")
    w("│ 15 │ recipes_bom                 │ 4. Nguyên Liệu & Kho BOM  │ PK: recipe_id, FKs: Prod/Size/Ingr, Định│")
    w("│ 16 │ inventory_checks            │ 4. Nguyên Liệu & Kho BOM  │ PK: check_id, FKs, Phiếu kiểm kê kho    │")
    w("│ 17 │ inventory_check_details     │ 4. Nguyên Liệu & Kho BOM  │ PK: detail_id, FKs: Check/Ingredient    │")
    w("├────┼─────────────────────────────┼───────────────────────────┼─────────────────────────────────────────┤")
    w("│ 18 │ customers                   │ 5. CRM & Quỹ Ly Takeaway  │ PK: customer_id, UK: phone, Hạng CRM    │")
    w("│ 19 │ orders                      │ 6. Đơn Hàng & Thanh Toán  │ PK: order_id, UK: order_code, 3 Kênh    │")
    w("│ 20 │ order_items                 │ 6. Đơn Hàng & Thanh Toán  │ PK: order_item_id, FKs: Order/Prod/Size │")
    w("│ 21 │ order_item_modifiers        │ 6. Đơn Hàng & Thanh Toán  │ PK: item_mod_id, FKs: Item/Modifier     │")
    w("│ 22 │ payments                    │ 6. Đơn Hàng & Thanh Toán  │ PK: payment_id, FK: order_id, PayOS/Cash│")
    w("│ 23 │ loyalty_cup_transactions    │ 6. CRM & Quỹ Ly Takeaway  │ PK: trans_id, FKs, Sổ cái Tích/Đổi 10 ly│")
    w("├────┼─────────────────────────────┼───────────────────────────┼─────────────────────────────────────────┤")
    w("│ 24 │ vouchers                    │ 7. Khuyến Mãi & AI Combo  │ PK: voucher_id, UK: code, Giảm %/Tiền   │")
    w("│ 25 │ customer_reviews            │ 7. CRM & Đánh Giá Món     │ PK: review_id, FKs, 1-5 Sao, Alert <= 2*│")
    w("│ 26 │ combos                      │ 7. Khuyến Mãi & AI Combo  │ PK: combo_id, UK: code, Luật Apriori    │")
    w("│ 27 │ combo_items                 │ 7. Khuyến Mãi & AI Combo  │ PK: combo_item_id, FKs: Combo/Product   │")
    w("├────┼─────────────────────────────┼───────────────────────────┼─────────────────────────────────────────┤")
    w("│ 28 │ shifts                      │ 8. Vận Hành & Ca Két HRM  │ PK: shift_id, FKs: Branch/User, Z-Report│")
    w("│ 29 │ attendances                 │ 8. Vận Hành & Ca Két HRM  │ PK: attendance_id, FKs: User/Br, BSSID/IP│")
    w("└────┴─────────────────────────────┴───────────────────────────┴─────────────────────────────────────────┘")
    w("```")
    w("")
    w("---")
    w("")
    w("## 1.3 Quy ước kiểu dữ liệu, tiền tệ và định lượng chính xác")
    w("")
    w("1. **Định danh duy nhất toàn cục (Universal Unique Identifiers):**")
    w("   - 100% Khóa chính (Primary Key) sử dụng kiểu dữ liệu `UUID` sinh tự động qua hàm `gen_random_uuid()` của PostgreSQL 16.")
    w("   - Tránh tuyệt đối xung đột khóa khi đồng bộ dữ liệu đa chi nhánh hoặc gộp dữ liệu phân tán.")
    w("2. **Đơn vị tiền tệ (Currency & Pricing):**")
    w("   - Sử dụng kiểu dữ liệu `DECIMAL(12,0)` cho toàn bộ các cột liên quan đến giá cả, phụ thu, giảm giá, phí ship và tổng tiền giao dịch.")
    w("   - Đồng Việt Nam (VNĐ) là đơn vị tiền tệ nguyên (không có số lẻ thập phân), đảm bảo tính toán tài chính chính xác tuyệt đối mà không gặp lỗi làm tròn dấu phẩy động (floating point errors).")
    w("   - Ràng buộc kiểm tra `CHECK (col >= 0)` được áp dụng cho 100% cột tài chính.")
    w("3. **Định lượng nguyên vật liệu & Định mức BOM (Formulation & Inventory):**")
    w("   - Sử dụng kiểu dữ liệu `DECIMAL(10,3)` cho định mức Bill of Materials và tồn kho nguyên liệu.")
    w("   - Đảm bảo độ chính xác đến $0.001$ gam hoặc $0.001$ ml (vd: $18.500$g cà phê bột, $25.000$ml sữa đặc).")
    w("4. **Dấu mốc thời gian (Timestamps & Timezones):**")
    w("   - Sử dụng kiểu dữ liệu `TIMESTAMPTZ` (Timestamp with Timezone, chuẩn UTC) cho mọi mốc thời gian (`created_at`, `updated_at`, `paid_at`, `check_in_time`, `opening_time`).")
    w("5. **Quản lý xóa mềm & Kiểm toán (Soft-Delete & Auditing):**")
    w("   - Các thực thể danh mục áp dụng cờ `is_deleted BOOLEAN DEFAULT FALSE`.")
    w("   - Mọi thay đổi cấu hình nhạy cảm được ghi lại tại `audit_logs` với cấu trúc `JSONB` thể hiện trạng thái `old_values` và `new_values`.")
    w("")
    w("---")
    w("")
    w("## 1.4 Hướng dẫn thực thi kịch bản (psql CLI, Docker Container & EF Core Code-First)")
    w("")
    w("### 1.4.1 Thực thi trực tiếp qua công cụ dòng lệnh `psql` (PostgreSQL CLI)")
    w("")
    w("```bash")
    w("# 1. Đăng nhập vào PostgreSQL và tạo Database mới")
    w("psql -h localhost -p 5432 -U postgres -c \"CREATE DATABASE smart_fb_db WITH ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C';\"")
    w("")
    w("# 2. Thực thi toàn bộ kịch bản DDL khởi tạo cấu trúc bảng, chỉ mục và triggers")
    w("psql -h localhost -p 5432 -U postgres -d smart_fb_db -f 01_schema_ddl.sql")
    w("")
    w("# 3. Thực thi kịch bản DML nạp bộ dữ liệu mẫu thực tế 100%")
    w("psql -h localhost -p 5432 -U postgres -d smart_fb_db -f 02_seed_data.sql")
    w("```")
    w("")
    w("### 1.4.2 Thực thi qua Docker Container")
    w("")
    w("```bash")
    w("# Khởi chạy container PostgreSQL 16")
    w("docker run --name smart_fb_postgres -e POSTGRES_PASSWORD=SmartFB@2026! -e POSTGRES_DB=smart_fb_db -p 5432:5432 -d postgres:16-alpine")
    w("")
    w("# Copy và thực thi kịch bản SQL trực tiếp vào container")
    w("docker exec -i smart_fb_postgres psql -U postgres -d smart_fb_db < Seed_Data_&_Database_Script.sql")
    w("```")
    w("")
    w("### 1.4.3 Tích hợp tự động trong .NET 8 Entity Framework Core")
    w("")
    w("```bash")
    w("# Áp dụng Migration và nạp Seed Data trong môi trường Development")
    w("cd d:\\Idea_DoAn\\src\\SmartFB.Infrastructure")
    w("dotnet ef database update --startup-project ..\\SmartFB.API")
    w("```")
    w("")
    w("---")
    w("")
    return "\n".join(lines)

print("Part 1 module loaded")
