# Generator for Seed_Data_&_Database_Script.md
import os

target_path = r"d:\Idea_DoAn\05_Quy_Chuan_&_Test_Cases\Seed_Data_&_Database_Script.md"

def build_content():
    lines = []
    w = lines.append

    w("# 💾 TÀI LIỆU THIẾT KẾ CƠ SỞ DỮ LIỆU & BỘ KỊCH BẢN DỮ LIỆU MẪU (DATABASE DDL & SEED DATA SPECIFICATION)")
    w("## HỆ THỐNG QUẢN LÝ VÀ VẬN HÀNH QUÁN CÀ PHÊ THÔNG MINH SMART F&B OS (v2.5.0)")
    w("")
    w("> [!IMPORTANT]")
    w("> **Mã tài liệu:** `SPEC-DB-SEED-01` | **Phiên bản:** `v2.5.0-Production-Ready`  ")
    w("> **Hệ quản trị CSDL đích:** PostgreSQL 16 Enterprise Relational Database Engine  ")
    w("> **Framework truy cập dữ liệu:** Entity Framework Core 8 (.NET 8 Clean Architecture) & Dapper High-Throughput  ")
    w("> **Chuẩn mực thiết kế:** 100% Chuẩn hóa 3NF (Third Normal Form), Khóa chính UUID v4 (`gen_random_uuid()`), Toàn vẹn tham chiếu (Foreign Keys & Cascade Rules), Ràng buộc kiểm tra (Check Constraints), Bộ chỉ mục kép B-Tree/GIN, Triggers tự động hóa, Sổ cái bất biến Audit Trail, và **ZERO Hardcoded Placeholders / Zero Ellipses (`...`)**.")
    w("")
    w("---")
    w("")
    w("## 📑 MỤC LỤC TOÀN DIỆN")
    w("")
    w("1. [CHƯƠNG 1: TỔNG QUAN KIẾN TRÚC DỮ LIỆU & NGUYÊN TẮC THIẾT KẾ 3NF](#chương-1-tổng-quan-kiến-trúc-dữ-liệu--nguyên-tắc-thiết-kế-3nf)")
    w("   - 1.1 [Khái quát hệ thống & 5 Trụ cột nghiệp vụ cốt lõi v2.5.0](#11-khái-quát-hệ-thống--5-trụ-cột-nghiệp-vụ-cốt-lõi-v250)")
    w("   - 1.2 [Ma trận 27 Thực thể Dữ liệu (Phân hệ 1 đến 8)](#12-ma-trận-27-thực-thể-dữ-liệu-phân-hệ-1-đến-8)")
    w("   - 1.3 [Quy ước kiểu dữ liệu, tiền tệ và định lượng chính xác](#13-quy-ước-kiểu-dữ-liệu-tiền-tệ-và-định-lượng-chính-xác)")
    w("   - 1.4 [Hướng dẫn thực thi kịch bản (psql CLI & EF Core Code-First)](#14-hướng-dẫn-thực-thi-kịch-bản-psql-cli--ef-core-code-first)")
    w("2. [CHƯƠNG 2: PHẦN I — TOÀN VĂN KỊCH BẢN DDL POSTGRESQL 16 (FULL SCHEMA SCRIPT)](#chương-2-phần-i--toàn-văn-kịch-bản-ddl-postgresql-16-full-schema-script)")
    w("   - 2.1 [Khởi tạo Extensions & Các kiểu dữ liệu liệt kê (ENUMs)](#21-khởi-tạo-extensions--các-kiểu-dữ-liệu-liệt-kê-enums)")
    w("   - 2.2 [Nhóm 1: Hệ thống, Cơ sở Chi nhánh & Bàn phục vụ QR](#22-nhóm-1-hệ-thống-cơ-sở-chi-nhánh--bàn-phục-vụ-qr)")
    w("   - 2.3 [Nhóm 2: Người dùng, Phân quyền RBAC & Nhật ký kiểm toán](#23-nhóm-2-người-dùng-phân-quyền-rbac--nhật-ký-kiểm-toán)")
    w("   - 2.4 [Nhóm 3: Thực đơn, Biến thể kích cỡ, Bảng giá vùng & Tùy chọn Modifiers](#24-nhóm-3-thực-đơn-biến-thể-kích-cỡ-bảng-giá-vùng--tùy-chọn-modifiers)")
    w("   - 2.5 [Nhóm 4: Nguyên vật liệu thô, Định mức BOM & Kiểm kê kho](#25-nhóm-4-nguyên-vật-liệu-thô-định-mức-bom--kiểm-kê-kho)")
    w("   - 2.6 [Nhóm 5: Đơn hàng đa kênh, Chi tiết món & Thanh toán VietQR / Tiền mặt](#26-nhóm-5-đơn-hàng-đa-kênh-chi-tiết-món--thanh-toán-vietqr--tiền-mặt)")
    w("   - 2.7 [Nhóm 6: CRM Khách hàng, Sổ cái tích 10 ly Takeaway, Vouchers & Đánh giá](#27-nhóm-6-crm-khách-hàng-sổ-cái-tích-10-ly-takeaway-vouchers--đánh-giá)")
    w("   - 2.8 [Nhóm 7: Quản lý Ca két tiền, Đối soát Z-Report & Chấm công khóa WiFi](#28-nhóm-7-quản-lý-ca-két-tiền-đối-soát-z-report--chấm-công-khóa-wifi)")
    w("   - 2.9 [Chiến lược Đánh chỉ mục hiệu năng cao (Composite B-Tree & GIN Indexes)](#29-chiến-lược-đánh-chỉ-mục-hiệu-năng-cao-composite-b-tree--gin-indexes)")
    w("   - 2.10 [Hàm tự động hóa & Database Triggers (`updated_at` & Alert <= 2 Sao)](#210-hàm-tự-động-hóa--database-triggers-updated_at--alert--2-sao)")
    w("3. [CHƯƠNG 3: PHẦN II — TOÀN VĂN KỊCH BẢN DML SEED DATA THỰC TẾ 100% (ZERO PLACEHOLDERS)](#chương-3-phần-ii--toàn-văn-kịch-bản-dml-seed-data-thực-tế-100-zero-placeholders)")
    w("   - 3.1 [Dữ liệu 3 Chi nhánh đại diện 3 miền & Cấu hình WiFi BSSID/Subnet](#31-dữ-liệu-3-chi-nhánh-đại-diện-3-miền--cấu-hình-wifi-bssidsubnet)")
    w("   - 3.2 [Dữ liệu Sơ đồ 30 Bàn phục vụ (10 bàn/chi nhánh) với mã QR Token](#32-dữ-liệu-sơ-đồ-30-bàn-phục-vụ-10-bànchi-nhánh-với-mã-qr-token)")
    w("   - 3.3 [Dữ liệu 10 Tài khoản Người dùng & Phân quyền RBAC (BCrypt Hash)](#33-dữ-liệu-10-tài-khoản-người-dùng--phân-quyền-rbac-bcrypt-hash)")
    w("   - 3.4 [Dữ liệu 5 Danh mục Thực đơn (Master Categories)](#34-dữ-liệu-5-danh-mục-thực-đơn-master-categories)")
    w("   - 3.5 [Dữ liệu 22 Món ăn / Đồ uống cơ sở (Master Products)](#35-dữ-liệu-22-món-ăn--đồ-uống-cơ-sở-master-products)")
    w("   - 3.6 [Dữ liệu Biến thể Kích cỡ Món ăn (`product_sizes`)](#36-dữ-liệu-biến-thể-kích-cỡ-món-ăn-product_sizes)")
    w("   - 3.7 [Dữ liệu Bảng giá vùng & Khóa món 86-Toggle theo chi nhánh (`product_branch_prices`)](#37-dữ-liệu-bảng-giá-vùng--khóa-món-86-toggle-theo-chi-nhánh-product_branch_prices)")
    w("   - 3.8 [Dữ liệu Tùy chọn Modifiers (Đường, Đá, Topping, Sữa) & Ma trận Liên kết](#38-dữ-liệu-tùy-chọn-modifiers-đường-đá-topping-sữa--ma-trận-liên-kết)")
    w("   - 3.9 [Dữ liệu 15 Nguyên vật liệu thô & Công thức định mức BOM chuẩn (`recipes_bom`)](#39-dữ-liệu-15-nguyên-vật-liệu-thô--công-thức-định-mức-bom-chuẩn-recipes_bom)")
    w("   - 3.10 [Dữ liệu 10 Hồ sơ Khách hàng CRM & Tiến trình Quỹ ly (0 đến 18 ly)](#310-dữ-liệu-10-hồ-sơ-khách-hàng-crm--tiến-trình-quỹ-ly-0-đến-18-ly)")
    w("   - 3.11 [Dữ liệu 6 Đơn hàng mẫu đại diện đa kênh & Giao dịch thanh toán đầy đủ](#311-dữ-liệu-6-đơn-hàng-mẫu-đại-diện-đa-kênh--giao-dịch-thanh-toán-đầy-đủ)")
    w("   - 3.12 [Dữ liệu Ca làm việc két tiền & Đối soát Z-Report (Khớp tiền & Lệch két +70k)](#312-dữ-liệu-ca-làm-việc-két-tiền--đối-soát-z-report-khớp-tiền--lệch-két-70k)")
    w("   - 3.13 [Dữ liệu Chấm công xác thực kép WiFi BSSID/IP Subnet](#313-dữ-liệu-chấm-công-xác-thực-kép-wifi-bssidip-subnet)")
    w("   - 3.14 [Dữ liệu Kiểm kê kho định kỳ & Đối chiếu hao hụt thực tế](#314-dữ-liệu-kiểm-kê-kho-định-kỳ--đối-chiếu-hao-hụt-thực-tế)")
    w("   - 3.15 [Dữ liệu Mã khuyến mãi Voucher giảm giá](#315-dữ-liệu-mã-khuyến-mãi-voucher-giảm-giá)")
    w("   - 3.16 [Dữ liệu Đánh giá phản hồi khách hàng (Kèm URL ảnh & Cảnh báo đỏ 2 sao)](#316-dữ-liệu-đánh-giá-phản-hồi-khách-hàng-kèm-url-ảnh--cảnh-báo-đỏ-2-sao)")
    w("   - 3.17 [Dữ liệu Gợi ý Combo thông minh AI Apriori (`combos` & `combo_items`)](#317-dữ-liệu-gợi-ý-combo-thông-minh-ai-apriori-combos--combo_items)")
    w("   - 3.18 [Dữ liệu Nhật ký kiểm toán hệ thống mẫu (`audit_logs`)](#318-dữ-liệu-nhật-ký-kiểm-toán-hệ-thống-mẫu-audit_logs)")
    w("4. [CHƯƠNG 4: PHẦN III — HƯỚNG DẪN TÍCH HỢP EF CORE 8 & TRUY VẤN KIỂM CHỨNG TOÀN DIỆN](#chương-4-phần-iii--hướng-dẫn-tích-hợp-ef-core-8--truy-vấn-kiểm-chứng-toàn-diện)")
    w("   - 4.1 [Lớp khởi tạo dữ liệu C# `DbInitializer.cs` (.NET 8 EF Core)](#41-lớp-khởi-tạo-dữ-liệu-c-dbinitializercs-net-8-ef-core)")
    w("   - 4.2 [Bộ 27 Truy vấn SQL Kiểm chứng Toàn vẹn Cơ sở Dữ liệu](#42-bộ-27-truy-vấn-sql-kiểm-chứng-toàn-vẹn-cơ-sở-dữ-liệu)")
    w("   - 4.3 [Checklist nghiệm thu kỹ thuật và lưu ý vận hành Production](#43-checklist-nghiệm-thu-kỹ-thuật-và-lưu-ý-vận-hành-production)")
    w("")
    return "\n".join(lines)

print("Header module ready")
